BudgetManagement/Models/PaginationViewModel.cs
namespace BudgetManagement.Models
{
    public class PaginationViewModel
    {
        public int Page { get; set; } = 1;
        private int recordsByPage = 10;
        private readonly int maxRecordsByPage = 50;

        public int RecordsByPage
        {
            get
            {
                return recordsByPage;
            }
            set
            {
                recordsByPage = (value > maxRecordsByPage) ? maxRecordsByPage : value;
            }
        }

        public int RecordsToSkip => recordsByPage * (Page - 1);
    }
}

BudgetManagement/Models/PriceSummaryViewModel.cs
namespace BudgetManagement.Models
{
    public class PriceSummaryViewModel
    {
        public int Income { get; set; }
        public int Expense { get; set; }
        public int Total { get; set; }
    }
}

BudgetManagement/Controllers/DealController.cs
using AutoMapper;
using BudgetManagement.Interfaces;
using BudgetManagement.Models;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;

namespace BudgetManagement.Controllers
{
    public class DealController : Controller
    {
        private readonly IDealRepository _dealRepository;
        private readonly IUserService _userService;
        private readonly IAccountRepository _accountRepository;
        private readonly IOperationTypeRepository _operationTypeRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly IMapper _mapper;
        private readonly IReportService _reportService;

        public DealController(
            IDealRepository dealRepository,
            IUserService userService,
            IAccountRepository accountRepository,
            IOperationTypeRepository operationTypeRepository,
            ICategoryRepository categoryRepository,
            IMapper mapper,
            IReportService reportService
        )
        {
            _dealRepository = dealRepository;
            _userService = userService;
            _accountRepository = accountRepository;
            _operationTypeRepository = operationTypeRepository;
            _categoryRepository = categoryRepository;
            _mapper = mapper;
            _reportService = reportService;
        }

        //Get: Index
        [HttpGet]
        public async Task<IActionResult> Index(int month, int year)
        {
            var userId = _userService.GetUserId();

            var model = await _reportService.GetDeateiledDealReport(userId, month, year, ViewBag);

            return View(model);
        }

        //Get: Weekly
        [HttpGet]
        public async Task<IActionResult> Weekly(int month, int year)
        {
            var userId = _userService.GetUserId();
            IEnumerable<WeeklyGetResult> dealsByWeek = await _reportService.GetWeeklyReport(userId, month, year, ViewBag);

            var grouped = dealsByWeek.GroupBy(x => x.Week)
                                     .Select(x => new WeeklyGetResult()
                                     {
                                         Week = x.Key,
                                         Income = x.Where(x => x.OperationTypeId == (int)OperationTypeEnum.Ingreso).Select(x => x.Price).FirstOrDefault(),
                                         Expense = x.Where(x => x.OperationTypeId == (int)OperationTypeEnum.Gasto).Select(x => x.Price).FirstOrDefault()
                                     }).ToList();

            if(year == 0 || month == 0)
            {
                var today = DateTime.Today;
                year = today.Year;
                month = today.Month;
            }

            var referenceDate = new DateTime(year, month, 1);
            var monthDays = Enumerable.Range(1, referenceDate.AddMonths(1).AddDays(-1).Day);
            var segmentedDays = monthDays.Chunk(7).ToList();

            for(int i = 0; i < segmentedDays.Count(); i++)
            {
                var week = i + 1;
                var beginDate = new DateTime(year, month, segmentedDays[i].First());
                var endDate = new DateTime(year, month, segmentedDays[i].Last());
                var weekGroup = grouped.FirstOrDefault(x => x.Week == week);

                if(weekGroup is null)
                {
                    grouped.Add(new WeeklyGetResult()
                    {
                        Week = week,
                        BeginDate = beginDate,
                        EndDate = endDate
                    });
                }
                else
                {
                    weekGroup.BeginDate = beginDate;
                    weekGroup.EndDate = endDate;
                }
            }

            grouped.OrderByDescending(x => x.Week).ToList();

            var model = new WeeklyReportViewModel();
            model.DealsByWeek = grouped;
            model.ReferenceDate = referenceDate;

            return View(model);
        }

        //Get: Monthly
        [HttpGet]
        public async Task<IActionResult> Monthly(int year)
        {
            var userId = _userService.GetUserId();

            if(year == 0)
            {
                year = DateTime.Now.Year;
            }

            var dealsByMonth = await _dealRepository.GetByMonth(userId, year);
            var groupedDeals = dealsByMonth.GroupBy(x => x.Month)
                                           .Select(x => new MonthlyGetResult()
                                           {
                                               Month = x.Key,
                                               Income = x.Where(x => x.OperationTypeId == (int)OperationTypeEnum.Ingreso).Select(x => x.Price).FirstOrDefault(),
                                               Expense = x.Where(x => x.OperationTypeId == (int)OperationTypeEnum.Gasto).Select(x => x.Price).FirstOrDefault()
                                           }).ToList();

            for(int month = 1; month <= 12; month++)
            {
                var deal = groupedDeals.FirstOrDefault(x => x.Month == month);
                var referenceDate = new DateTime(year, month, 1);

                if(deal is null)
                {
                    groupedDeals.Add(new MonthlyGetResult()
                    {
                        Month = month,
                        ReferenceDate = referenceDate
                    });
                }
                else
                {
                    deal.ReferenceDate = referenceDate;
                }
            }

            groupedDeals = groupedDeals.OrderByDescending(x => x.Month).ToList();

            var model = new MonthlyReportViewModel();
            model.Year = year;
            model.DealsByMonth = groupedDeals;

            return View(model);
        }

        //Get: ExcelReport
        [HttpGet]
        public IActionResult ExcelReport()
        {
            return View();
        }

        /// <summary>
        /// Method to generate an Excel file of a month
        /// </summary>
        /// <param name="month">Given month</param>
        /// <param name="year">Given year</param>
        /// <returns></returns>
        [HttpGet]
        public async Task<FileResult> ExportExcelByMonth(int month, int year)
        {
            var beginDate = new DateTime(year, month, 1);
            var endDate = beginDate.AddMonths(1).AddDays(-1);
            var userId = _userService.GetUserId();

            var deals = await _dealRepository.GetByUserId(new DealByUserParameter()
            {
                UserId = userId,
                BeginDate = beginDate,
                EndDate = endDate
            });

            var fileName = $"Manejo_Presupuesto-{beginDate.ToString("MMM yyyy")}.xlsx";
            return GenerateExcel(fileName, deals);
        }

        /// <summary>
        /// Method to generate an Excel file of a year
        /// </summary>
        /// <param name="year">Given year</param>
        /// <returns></returns>
        [HttpGet]
        public async Task<FileResult> ExportExcelByYear(int year)
        {
            var beginDate = new DateTime(year, 1, 1);
            var endDate = beginDate.AddYears(1).AddDays(-1);
            var userId = _userService.GetUserId();

            var deals = await _dealRepository.GetByUserId(new DealByUserParameter()
            {
                UserId = userId,
                BeginDate = beginDate,
                EndDate = endDate
            });

            var fileName = $"Manejo_Presupuesto-{beginDate.ToString("yyyy")}.xlsx";
            return GenerateExcel(fileName, deals);
        }

        /// <summary>
        /// Method to generate an Excel file with all the data
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<FileResult> ExportExcelAll()
        {
            var beginDate = DateTime.Today.AddYears(-100);
            var endDate = DateTime.Today.AddYears(100);
            var userId = _userService.GetUserId();

            var deals = await _dealRepository.GetByUserId(new DealByUserParameter()
            {
                UserId = userId,
                BeginDate = beginDate,
                EndDate = endDate
            });

            var fileName = $"Manejo_Presupuesto-{DateTime.Today.ToString("dd-MM-yyyy")}.xlsx";
            return GenerateExcel(fileName, deals);
        }

        /// <summary>
        /// Method to generate an Excel File
        /// </summary>
        /// <param name="fileName">Name for the file</param>
        /// <param name="deals">IEnumerable with the collection of data</param>
        /// <returns></returns>
        private FileResult GenerateExcel(string fileName, IEnumerable<Deal> deals)
        {
            DataTable dt = new DataTable("Deals");
            dt.Columns.AddRange(new DataColumn[]
            {
                new DataColumn("Fecha"),
                new DataColumn("Cuenta"),
                new DataColumn("Categoría"),
                new DataColumn("Nota"),
                new DataColumn("Monto"),
                new DataColumn("Ingreso/Gasto")
            });

            foreach(var deal in deals)
            {
                string operationType = ((OperationTypeEnum)deal.OperationTypeId).ToString();
                dt.Rows.Add(deal.DealDate, deal.Account, deal.Category, deal.Note, deal.Price, operationType);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);

                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
                }
            }
        }

        //Get: Calendar

BudgetManagement/Views/Shared/_BrowseByMonths.cshtml
@model DateTime

<h4>
    <a asp-route-month="@ViewBag.PreviousMonth" asp-route-year="@ViewBag.PreviousYear"
       class="btn btn-secondary">
        <i class="bi-chevron-left"></i>
    </a>
    @Model.ToString("MMM")-@Model.Year
    <a asp-route-month="@ViewBag.NextMonth" asp-route-year="@ViewBag.NextYear"
       class="btn btn-secondary">
        <i class="bi-chevron-right"></i>
    </a>
</h4>

BudgetManagement/Views/Shared/_DetailedDealReport.cshtml
@model DetailDealReport

@{
    var priceSummary = new PriceSummaryViewModel()
    {
        Income = Model.DepositBalance,
        Expense = Model.WithdrawBalance,
        Total = Model.Total
    };
}

<partial name="_BrowseByMonths" model="@Model.BeginDate" />

<partial name="_PriceSummary" model="@priceSummary" />

@if (Model.GroupedDeals.Count() == 0)
{
    <h5>No hay datos para mostrar</h5>
}
else
{
    <table class="table">
        <tbody>
            @foreach (var groupedDeal in Model.GroupedDeals)
            {
                <tr style="background-color: lightblue; font-size: 26px;">
                    <td colspan="3">
                        @groupedDeal.DealDate.Day
                        <span class="badge bg-secondary">
                            @groupedDeal.DealDate.ToString("ddd")
                        </span>
                    </td>
                    <td class="active_element">@groupedDeal.DepositBalance.ToString("N0")</td>
                    <td class="passive_element">@groupedDeal.WithdrawBalance.ToString("N0")</td>
                </tr>
                @foreach (var deal in groupedDeal.Deals)
                {
                    <tr style="vertical-align: middle;">
                        <td>
                            <a asp-controller="Deal" asp-action="Edit" asp-route-id="@deal.Id" asp-route-returnUrl="@ViewBag.ReturnUrl">
                                <i class="bi-pencil"></i>
                            </a>
                        </td>
                        <td>@deal.Category</td>
                        <td>@deal.Account</td>
                        <td class="active_element">
                            @(deal.OperationTypeId == (int)OperationTypeEnum.Ingreso ? deal.Price.ToString("N0") : null)
                        </td>
                        <td class="passive_element">
                            @(deal.OperationTypeId == (int)OperationTypeEnum.Gasto ? deal.Price.ToString("N0") : null)
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
}

BudgetManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Manejo de Cuentas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BudgetManagement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/custom.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/fullcalendar/main.min.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Deal" asp-action="Index">ManejoDeCuentas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Deal" asp-action="Index">Transacciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="Index">Cuentas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="AccountType" asp-action="Index">Tipos de Cuenta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="OperationType" asp-action="Index">Tipos de Operación</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Category" asp-action="Index">Categorías</a>
                        </li>
                    </ul>
                    <partial name="_LinksLogin" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BudgetManagement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BudgetManagement/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<AppUser> SignInManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link text-dark">Hola, @User.Identity.Name</span>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-action="Logout" asp-controller="AppUser">
                <button type="submit" class="nav-link btn btn-link text-dark">
                    Cerrar Sesión
                </button>
            </form>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="AppUser" asp-action="Register">
                Registro
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="AppUser" asp-action="Login">
                Iniciar Sesión
            </a>
        </li>

    }
</ul>

BudgetManagement/Views/Shared/_Pagination.cshtml
@model PaginationResponse

@{
    var layoutLink = string.Concat(Model.BaseUrl, "?page={0}&recordsByPage={1}");
    var enablePrevButton = Model.Page > 1;
    var enableNextButton = Model.Page < Model.AmountOfPages;
}

<nav>
    <ul class="pagination">
        <li class="page-item @(enablePrevButton ? null : "disabled")">
            @if (enablePrevButton)
            {
                <a class="page-link" href="@string.Format(layoutLink, Model.Page - 1, Model.RecordsByPage)">
                    Anterior
                </a>
            }
            else
            {
                <span class="page-link">
                    Anterior
                </span>
            }

        </li>
        @for (var current = 1; current <= Model.AmountOfPages; current++)
        {
            <li class="page-item @(current == Model.Page ? "active" : null)">
                <a class="page-link" href="@string.Format(layoutLink, current, Model.RecordsByPage)">
                    @current
                </a>
            </li>
        }
        <li class="page-item @(enableNextButton ? null : "disabled")">
            @if (enableNextButton)
            {
                <a class="page-link" href="@string.Format(layoutLink, Model.Page + 1, Model.RecordsByPage)">
                    Siguiente
                </a>
            }
            else
            {
                <span class="page-link">
                    Siguiente
                </span>
            }
        </li>
    </ul>
</nav>

BudgetManagement/Views/Shared/_PriceSummary.cshtml
@model PriceSummaryViewModel

<div class="totals-container mb-3">
    <div>
        <div>
            <strong>Depósitos</strong>
        </div>
        <div class="active_element">
            @Model.Income.ToString("N0")
        </div>
    </div>
    <div>
        <div>
            <strong>Retiros</strong>
        </div>
        <div class="passive_element">
            @Model.Expense.ToString("N0")
        </div>
    </div>
    <div>
        <div>
            <strong>Total</strong>
        </div>
        <div>
            @Model.Total.ToString("N0")
        </div>
    </div>
</div>